/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppBillingRouteImport } from './routes/_app/billing'
import { Route as AppBusinessRouteImport } from './routes/_app/business'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppClientsRouteImport } from './routes/_app/clients'
import { Route as AppContentRouteImport } from './routes/_app/content'
import { Route as AppEnquiriesRouteImport } from './routes/_app/enquiries'
import { Route as AppIncidentsRouteImport } from './routes/_app/incidents'
import { Route as AppMediaRouteImport } from './routes/_app/media'
import { Route as AppMonitorsRouteImport } from './routes/_app/monitors'
import { Route as AppPrivacyRouteImport } from './routes/_app/privacy'
import { Route as AppRenewalsRouteImport } from './routes/_app/renewals'
import { Route as AppRequestsRouteImport } from './routes/_app/requests'
import { Route as AppSitesRouteImport } from './routes/_app/sites'
import { Route as AppStoreRouteImport } from './routes/_app/store'
import { Route as AppTermsRouteImport } from './routes/_app/terms'
import { Route as AppVisitorsRouteImport } from './routes/_app/visitors'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ApiPublicSiteRouteImport } from './routes/api/public/site'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppBusinessRoute = AppBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppContentRoute = AppContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AppRoute,
} as any)
const AppEnquiriesRoute = AppEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => AppRoute,
} as any)
const AppIncidentsRoute = AppIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AppRoute,
} as any)
const AppMediaRoute = AppMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AppRoute,
} as any)
const AppMonitorsRoute = AppMonitorsRouteImport.update({
  id: '/monitors',
  path: '/monitors',
  getParentRoute: () => AppRoute,
} as any)
const AppPrivacyRoute = AppPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AppRoute,
} as any)
const AppRenewalsRoute = AppRenewalsRouteImport.update({
  id: '/renewals',
  path: '/renewals',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsRoute = AppRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AppRoute,
} as any)
const AppSitesRoute = AppSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AppRoute,
} as any)
const AppStoreRoute = AppStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AppRoute,
} as any)
const AppTermsRoute = AppTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => AppRoute,
} as any)
const AppVisitorsRoute = AppVisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => AppRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSiteRoute = ApiPublicSiteRouteImport.update({
  id: '/api/public/site',
  path: '/api/public/site',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/': typeof AppIndexRoute
  '/set-password': typeof SetPasswordRoute
  '/admin': typeof AppAdminRoute
  '/billing': typeof AppBillingRoute
  '/business': typeof AppBusinessRoute
  '/calendar': typeof AppCalendarRoute
  '/clients': typeof AppClientsRoute
  '/content': typeof AppContentRoute
  '/enquiries': typeof AppEnquiriesRoute
  '/incidents': typeof AppIncidentsRoute
  '/media': typeof AppMediaRoute
  '/monitors': typeof AppMonitorsRoute
  '/privacy': typeof AppPrivacyRoute
  '/renewals': typeof AppRenewalsRoute
  '/requests': typeof AppRequestsRoute
  '/sites': typeof AppSitesRoute
  '/store': typeof AppStoreRoute
  '/terms': typeof AppTermsRoute
  '/visitors': typeof AppVisitorsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/public/site': typeof ApiPublicSiteRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/set-password': typeof SetPasswordRoute
  '/admin': typeof AppAdminRoute
  '/billing': typeof AppBillingRoute
  '/business': typeof AppBusinessRoute
  '/calendar': typeof AppCalendarRoute
  '/clients': typeof AppClientsRoute
  '/content': typeof AppContentRoute
  '/enquiries': typeof AppEnquiriesRoute
  '/incidents': typeof AppIncidentsRoute
  '/media': typeof AppMediaRoute
  '/monitors': typeof AppMonitorsRoute
  '/privacy': typeof AppPrivacyRoute
  '/renewals': typeof AppRenewalsRoute
  '/requests': typeof AppRequestsRoute
  '/sites': typeof AppSitesRoute
  '/store': typeof AppStoreRoute
  '/terms': typeof AppTermsRoute
  '/visitors': typeof AppVisitorsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof AppIndexRoute
  '/api/public/site': typeof ApiPublicSiteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/_app': typeof AppRouteWithChildren
  '/set-password': typeof SetPasswordRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/business': typeof AppBusinessRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/clients': typeof AppClientsRoute
  '/_app/content': typeof AppContentRoute
  '/_app/enquiries': typeof AppEnquiriesRoute
  '/_app/incidents': typeof AppIncidentsRoute
  '/_app/media': typeof AppMediaRoute
  '/_app/monitors': typeof AppMonitorsRoute
  '/_app/privacy': typeof AppPrivacyRoute
  '/_app/renewals': typeof AppRenewalsRoute
  '/_app/requests': typeof AppRequestsRoute
  '/_app/sites': typeof AppSitesRoute
  '/_app/store': typeof AppStoreRoute
  '/_app/terms': typeof AppTermsRoute
  '/_app/visitors': typeof AppVisitorsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_app/': typeof AppIndexRoute
  '/api/public/site': typeof ApiPublicSiteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/'
    | '/set-password'
    | '/admin'
    | '/billing'
    | '/business'
    | '/calendar'
    | '/clients'
    | '/content'
    | '/enquiries'
    | '/incidents'
    | '/media'
    | '/monitors'
    | '/privacy'
    | '/renewals'
    | '/requests'
    | '/sites'
    | '/store'
    | '/terms'
    | '/visitors'
    | '/auth/callback'
    | '/api/public/site'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/set-password'
    | '/admin'
    | '/billing'
    | '/business'
    | '/calendar'
    | '/clients'
    | '/content'
    | '/enquiries'
    | '/incidents'
    | '/media'
    | '/monitors'
    | '/privacy'
    | '/renewals'
    | '/requests'
    | '/sites'
    | '/store'
    | '/terms'
    | '/visitors'
    | '/auth/callback'
    | '/'
    | '/api/public/site'
  id:
    | '__root__'
    | '/$'
    | '/_app'
    | '/set-password'
    | '/_app/admin'
    | '/_app/billing'
    | '/_app/business'
    | '/_app/calendar'
    | '/_app/clients'
    | '/_app/content'
    | '/_app/enquiries'
    | '/_app/incidents'
    | '/_app/media'
    | '/_app/monitors'
    | '/_app/privacy'
    | '/_app/renewals'
    | '/_app/requests'
    | '/_app/sites'
    | '/_app/store'
    | '/_app/terms'
    | '/_app/visitors'
    | '/auth/callback'
    | '/_app/'
    | '/api/public/site'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  AppRoute: typeof AppRouteWithChildren
  SetPasswordRoute: typeof SetPasswordRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ApiPublicSiteRoute: typeof ApiPublicSiteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/business': {
      id: '/_app/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof AppBusinessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients': {
      id: '/_app/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/content': {
      id: '/_app/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof AppContentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/enquiries': {
      id: '/_app/enquiries'
      path: '/enquiries'
      fullPath: '/enquiries'
      preLoaderRoute: typeof AppEnquiriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/incidents': {
      id: '/_app/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof AppIncidentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/media': {
      id: '/_app/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof AppMediaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/monitors': {
      id: '/_app/monitors'
      path: '/monitors'
      fullPath: '/monitors'
      preLoaderRoute: typeof AppMonitorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/privacy': {
      id: '/_app/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof AppPrivacyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/renewals': {
      id: '/_app/renewals'
      path: '/renewals'
      fullPath: '/renewals'
      preLoaderRoute: typeof AppRenewalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/requests': {
      id: '/_app/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AppRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sites': {
      id: '/_app/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof AppSitesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/store': {
      id: '/_app/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof AppStoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/terms': {
      id: '/_app/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof AppTermsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/visitors': {
      id: '/_app/visitors'
      path: '/visitors'
      fullPath: '/visitors'
      preLoaderRoute: typeof AppVisitorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/site': {
      id: '/api/public/site'
      path: '/api/public/site'
      fullPath: '/api/public/site'
      preLoaderRoute: typeof ApiPublicSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppBillingRoute: typeof AppBillingRoute
  AppBusinessRoute: typeof AppBusinessRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppClientsRoute: typeof AppClientsRoute
  AppContentRoute: typeof AppContentRoute
  AppEnquiriesRoute: typeof AppEnquiriesRoute
  AppIncidentsRoute: typeof AppIncidentsRoute
  AppMediaRoute: typeof AppMediaRoute
  AppMonitorsRoute: typeof AppMonitorsRoute
  AppPrivacyRoute: typeof AppPrivacyRoute
  AppRenewalsRoute: typeof AppRenewalsRoute
  AppRequestsRoute: typeof AppRequestsRoute
  AppSitesRoute: typeof AppSitesRoute
  AppStoreRoute: typeof AppStoreRoute
  AppTermsRoute: typeof AppTermsRoute
  AppVisitorsRoute: typeof AppVisitorsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppBillingRoute: AppBillingRoute,
  AppBusinessRoute: AppBusinessRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppClientsRoute: AppClientsRoute,
  AppContentRoute: AppContentRoute,
  AppEnquiriesRoute: AppEnquiriesRoute,
  AppIncidentsRoute: AppIncidentsRoute,
  AppMediaRoute: AppMediaRoute,
  AppMonitorsRoute: AppMonitorsRoute,
  AppPrivacyRoute: AppPrivacyRoute,
  AppRenewalsRoute: AppRenewalsRoute,
  AppRequestsRoute: AppRequestsRoute,
  AppSitesRoute: AppSitesRoute,
  AppStoreRoute: AppStoreRoute,
  AppTermsRoute: AppTermsRoute,
  AppVisitorsRoute: AppVisitorsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  AppRoute: AppRouteWithChildren,
  SetPasswordRoute: SetPasswordRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ApiPublicSiteRoute: ApiPublicSiteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
